DROP TABLE IF EXISTS MOVIES;
 
CREATE TABLE MOVIES (
  move_id INT AUTO_INCREMENT  PRIMARY KEY,
  movie_name VARCHAR(250) NOT NULL,
  movie_desc VARCHAR(250) NULL,
  rating VARCHAR(250) DEFAULT NULL,
  rating_givenby VARCHAR(250) DEFAULT NULL
);